- name: Setup Apache Tomcat
  hosts: web
  become: yes
  tasks: 
  - name : Update Instance
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes

  - name: Install default-jdk
    ansible.builtin.apt:
      name: default-jdk
      state: present

  - name: Create group "tomcat"
    ansible.builtin.group:
      name: somegroup
      state: present    