- name: Copy task
  hosts: localhost
  become: yes
  tasks: 
  - name: Install httpd
    ansible.builtin.yum:
      name: httpd
      state: installed
                
                
  - name: Start httpd
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Copy file to remote location
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html